# Generated by Django 5.2.6 on 2025-09-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classsession",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="classsession",
            name="unique_teacher_class_start",
        ),
        migrations.AlterModelTable(
            name="classsession",
            table=None,
        ),
    ]
