# Generated by Django 5.2.6 on 2025-09-28 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0002_alter_classsession_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classsession",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="classsession",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrolled_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
