# Generated by Django 5.2.6 on 2025-09-28 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_remove_classsession_created_at_and_more"),
        ("engagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engagementreport",
            name="emotion_counts",
        ),
        migrations.RemoveField(
            model_name="engagementreport",
            name="low_attention_pct",
        ),
        migrations.RemoveField(
            model_name="engagementreport",
            name="max_engagement",
        ),
        migrations.RemoveField(
            model_name="engagementreport",
            name="pdf_report",
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="engagementreport",
            name="avg_engagement",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="engagementreport",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="classrooms.classsession",
            ),
        ),
        migrations.AlterField(
            model_name="engagementreport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagement_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
