# Generated by Django 5.2.6 on 2025-09-29 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_remove_classsession_created_at_and_more"),
        ("engagement", "0002_remove_engagementreport_emotion_counts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="engagementreport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="angry",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="attention",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="dominant_emotion",
            field=models.CharField(default="Neutral", max_length=50),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="happy",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="neutral",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="sad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engagementreport",
            name="surprise",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="engagementreport",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classrooms.classsession",
            ),
        ),
        migrations.AlterField(
            model_name="engagementreport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="engagementreport",
            table=None,
        ),
        migrations.RemoveField(
            model_name="engagementreport",
            name="notes",
        ),
    ]
